localization-appendices: Appendices
localization-chapters: Chapters
localization-draft: Draft
localization-index: Contents
localization-top: Top
localization-type-appendix: Appendix
localization-type-biblio: Bibliography
localization-type-chapter: Chapter
localization-type-index: Contents
localization-type-standalone: Preface
